name: Dispatch

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:

  dispatch:

    name: dispatch to validate repo
    runs-on: ubuntu-latest
      
    steps:
      - run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }} " \
          -H 'Accept: application/vnd.github.everest-preview+json' "https://api.github.com/repos/rw-bsi/validate/dispatches" \
          -d '{ "event_type": "submodule_dispatch", "client_payload": { "repo": "ifc-validation-data-model", "branch": "development" } }'
